import { User } from '../../user/entities/user.entity';
import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  ManyToOne,
  JoinColumn,
  Index,
} from 'typeorm';
import { ReportStatus } from '../constants/report-status.enum';

/**
 * Persists post-match analysis reports.
 *
 * Each report is uniquely identified by (event_id, team_id).
 * The compound unique index prevents duplicate analyses for the same match.
 */
@Entity('postmatch_reports')
@Index(['event_id', 'team_id'], { unique: true })
export class PostMatchReport {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  // ─── Match Identifiers ───────────────────────────────────────────────────

  @Column({ type: 'varchar', length: 100 })
  @Index()
  event_id: string;

  @Column({ type: 'varchar', length: 100 })
  team_id: string;

  // ─── Report Content ──────────────────────────────────────────────────────

  /** Full structured JSON returned by the AI microservice. */
  @Column({ type: 'jsonb' })
  raw_analysis: object;

  /** Human-readable explanation generated by the LLM. Null if LLM failed. */
  @Column({ type: 'text', nullable: true })
  llm_explanation: string | null;

  /** Which LLM model produced the explanation (e.g. "gemini-2.0-flash"). */
  @Column({ type: 'varchar', length: 100, nullable: true })
  llm_model: string | null;

  // ─── Status ──────────────────────────────────────────────────────────────

  @Column({
    type: 'enum',
    enum: ReportStatus,
    default: ReportStatus.COMPLETED,
  })
  status: ReportStatus;

  // ─── Ownership ───────────────────────────────────────────────────────────

  /** The club this report belongs to (multi-tenant isolation). */
  @Column({ type: 'uuid' })
  @Index()
  club_id: string;

  /** The user who triggered this analysis (audit trail). */
  @Column({ type: 'uuid' })
  requested_by_id: string;

  @ManyToOne(() => User, { nullable: false, onDelete: 'CASCADE' })
  @JoinColumn({ name: 'requested_by_id' })
  requested_by: User;

  // ─── Timestamps ──────────────────────────────────────────────────────────

  /** Timestamp from the AI analysis (set by the AI service). */
  @Column({ type: 'timestamptz', nullable: true })
  analysis_timestamp: Date | null;

  @CreateDateColumn()
  created_at: Date;

  @UpdateDateColumn()
  updated_at: Date;
}
