import { ApiProperty } from '@nestjs/swagger';

/**
 * Data Transfer Object containing the generated Cloudinary signature and configuration
 * required by the frontend to perform the direct-to-cloud upload.
 */
export class StorageSignatureResDto {
  /**
   * The generated Cloudinary upload signature
   * @example 'a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1'
   */
  @ApiProperty({
    description: 'The secure SHA-1 signature generated by the backend',
    example: 'a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1',
  })
  signature: string;

  /**
   * The timestamp when the signature was generated (in seconds)
   * @example 17181920
   */
  @ApiProperty({
    description: 'The Unix timestamp (in seconds) used to sign the request',
    example: 17181920,
  })
  timestamp: number;

  /**
   * The semantic public ID generated for this file upload
   * @example 'e2e604f2-95f3-4fb0-86c3-1ad394ea7d08_profile_image_17181920'
   */
  @ApiProperty({
    description: 'The semantic public_id generated for the file in Cloudinary',
    example: 'e2e604f2-95f3-4fb0-86c3-1ad394ea7d08_profile_image_17181920',
  })
  public_id: string;

  /**
   * The target folder in Cloudinary
   * @example 'profile-image'
   */
  @ApiProperty({
    description: 'The folder in Cloudinary where the file will be uploaded',
    example: 'profile-image',
  })
  folder: string;

  /**
   * The Cloudinary Cloud Name
   * @example 'dpnrrr7lo'
   */
  @ApiProperty({
    description: 'The Cloudinary Cloud Name identifier',
    example: 'dpnrrr7lo',
  })
  cloud_name: string;

  /**
   * The Cloudinary API Key
   * @example '555635433416118'
   */
  @ApiProperty({
    description: 'The Cloudinary API Key to authorize the upload',
    example: '555635433416118',
  })
  api_key: string;

  /**
   * The full direct upload endpoint URL
   * @example 'https://api.cloudinary.com/v1_1/dpnrrr7lo/auto/upload'
   */
  @ApiProperty({
    description: 'The full direct upload endpoint URL on Cloudinary API',
    example: 'https://api.cloudinary.com/v1_1/dpnrrr7lo/auto/upload',
  })
  upload_url: string;

  /**
   * Whether to overwrite the file if it already exists
   * @example 'false'
   */
  @ApiProperty({
    description: 'Whether to overwrite the file if it already exists',
    example: 'false',
  })
  overwrite: 'true' | 'false';
}
